services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_sql_itreasury
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4"
    #       memory: 5G
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itreasury_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: C:/Cloning
        target: /dump
    networks:
      - spring-network
    restart: unless-stopped

#  itreasury-api:
#    container_name: itreasury-api
#    image: vitira/itreasury:latest
#    ports:
#      - "8090:8090"
#    networks:
#      - spring-network
#    depends_on:
#      - postgres_db
  
  keycloak:
     container_name: keycloak-itreasury
     image: quay.io/keycloak/keycloak:24.0
     ports:
       - 9090:8080
     environment:
       KEYCLOAK_ADMIN: admin
       KEYCLOAK_ADMIN_PASSWORD: admin
     networks:
       - spring-network
     command:
       - "start-dev"

networks:
  spring-network:
    driver: bridge

volumes:
   postgres:
     driver: local
   keycloak:
     driver: local