server:
    port: 8090
    servlet:
        context-path: /api/v1
spring:
  application:
    name: itreasury
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: itreasury-pool
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 2000000
      leak-detection-threshold: 15000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # format_sql: true
  # flyway:
  #   enabled: true
  #   locations: classpath:db/migration
  #   baseline-on-migrate: true
  
  mail:
    imap:
      host: ${MAIL_IMAP_HOST:imap.gmail.com}
      port: ${MAIL_IMAP_PORT:993}
      username: ${MAIL_IMAP_USERNAME:noreply.vitira@gmail.com}
      password: ${G_PASS:YOUR-GMAIL-APP-PASSWORD}
      protocol: imaps
      starttls:
        enable: true
    email:
      provider: ${MAIL_EMAIL_PROVIDER:gmail}

jwt:
  secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400}

# logging:
#   level:
#     root: INFO
#     com.vitira.itreasury: DEBUG
#     org.springframework.security: DEBUG
#     org.springframework.web: DEBUG